org: luyza
app: uiuibiometrics
service: backend

provider:
  name: aws
  runtime: python3.11
  region: eu-north-1
  stage: ${opt:stage, 'dev'}
  memorySize: 1024
  environment:
    DYNAMODB_TABLE: uiui-biometrics-${self:provider.stage}
    STAGE: ${self:provider.stage}
    AVATAR_BUCKET: uiui-avatars-${self:provider.stage}
    USER_POOL_ID: "eu-north-1_aBOOx7l1A"

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:DeleteItem
        - dynamodb:UpdateItem
        - dynamodb:PutItem
        - dynamodb:Query
        - dynamodb:BatchWriteItem
      Resource:
        - !GetAtt UiuibiometricsTable.Arn
        - !Join [ '/', [ !GetAtt UiuibiometricsTable.Arn, 'index', '*' ] ]
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:GetObject
      Resource:
        - "arn:aws:s3:::uiui-avatars-${self:provider.stage}/*"
    - Effect: Allow
      Action:
        - cognito-idp:AdminGetUser
        - cognito-idp:AdminListGroupsForUser
      Resource:
        - "arn:aws:cognito-idp:${self:provider.region}:*:userpool/eu-north-1_aBOOx7l1A"


  httpApi:
    authorizers:
      serviceAuthorizer:
        type: jwt
        identitySource: $request.header.Authorization
        issuerUrl: https://cognito-idp.${aws:region}.amazonaws.com/eu-north-1_aBOOx7l1A
        audience:
          - 3a7gjc7aq8v5auneeuqtfvcb1a

custom:
  serverless-offline:
    ignoreJWTSignature: true
    httpTimeout: 60000

  pythonRequirements:
    dockerizePip: true
    zip: true
    slim: true

  plugins:
    local:
      list: [
        serverless-s3-local,
        serverless-dynamodb,
        serverless-offline,
        serverless-python-requirements
      ]
    dev:
      list: [ serverless-python-requirements ]
    acc:
      list: [ serverless-python-requirements ]
    prod:
      list: [ serverless-python-requirements ]

  s3:
    host: localhost
    port: 4569
    directory: ./offline/s3
    cors: false
    buckets:
      - uiui-avatars-${self:provider.stage}

  serverless-dynamodb:
    stages:
      - local
    start:
      port: 8011
      inMemory: true
      migrate: true
      seed: true
    seed:
      local:
        sources:
          - table: uiui-biometrics-${self:provider.stage}
            sources: [ ./offline/migrations/uiui.json ]

functions:
  profileRouter:
    handler: src/http_handlers/profile/routes.handler
    events:
      - httpApi:
          path: /api/profile
          method: ANY
          authorizer:
            name: serviceAuthorizer
      - httpApi:
          path: /api/profile/{proxy+}
          method: ANY
          authorizer:
            name: serviceAuthorizer

  assessmentRouter:
    handler: src/http_handlers/assessment/routes.handler
    timeout: 25
    events:
      - httpApi:
          path: /api/assessments
          method: ANY
          authorizer:
            name: serviceAuthorizer
      - httpApi:
          path: /api/assessments/{proxy+}
          method: ANY
          authorizer:
            name: serviceAuthorizer
  visionRouter:
    handler: src/http_handlers/vision/routes.handler
    timeout: 29
    events:
      - httpApi:
          path: /api/analyze
          method: ANY
          authorizer:
            name: serviceAuthorizer
      - httpApi:
          path: /api/analyze/{proxy+}
          method: ANY
          authorizer:
            name: serviceAuthorizer
  menuRouter:
    handler: src/http_handlers/menu/routes.handler
    timeout: 29
    events:
      - httpApi:
          path: /api/menu
          method: ANY
          authorizer:
            name: serviceAuthorizer
      - httpApi:
          path: /api/menu/{proxy+}
          method: ANY
          authorizer:
            name: serviceAuthorizer
  doctorRouter:
    handler: src/http_handlers/doctor/routes.handler
    timeout: 29
    events:
      - httpApi:
          path: /api/doctor
          method: ANY
          authorizer:
            name: serviceAuthorizer
      - httpApi:
          path: /api/doctor/{proxy+}
          method: ANY
          authorizer:
            name: serviceAuthorizer
  notificationRouter:
    handler: src/http_handlers/notification/routes.handler
    events:
      - httpApi:
          path: /api/notifications
          method: ANY
          authorizer:
            name: serviceAuthorizer
      - httpApi:
          path: /api/notifications/{proxy+}
          method: ANY
          authorizer:
            name: serviceAuthorizer
  cronProcessExpiredMenus:
    handler: src/http_handlers/menu/cron_expired_menus
    events:
      - schedule: rate(1 minute)

plugins:
  ${self:custom.plugins.${self:provider.stage}.list}

resources:
  Resources:
    UiuibiometricsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: uiui-biometrics-${self:provider.stage}
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
          - AttributeName: GSI1_PK
            AttributeType: S
          - AttributeName: GSI1_SK
            AttributeType: S
          - AttributeName: GSI2_PK
            AttributeType: S
          - AttributeName: GSI2_SK
            AttributeType: S
          - AttributeName: GSI3_PK
            AttributeType: S
          - AttributeName: GSI3_SK
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: GSI1
            KeySchema:
              - AttributeName: GSI1_PK
                KeyType: HASH
              - AttributeName: GSI1_SK
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
          - IndexName: GSI2
            KeySchema:
              - AttributeName: GSI2_PK
                KeyType: HASH
              - AttributeName: GSI2_SK
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
          - IndexName: GSI3
            KeySchema:
              - AttributeName: GSI3_PK
                KeyType: HASH
              - AttributeName: GSI3_SK
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST
    AvatarBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: uiui-avatars-${self:provider.stage}
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders:
                - "*"
              AllowedMethods:
                - GET
                - PUT
              AllowedOrigins:
                - "*"